logging:
  config: classpath:log4j2.yml
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

spring:
  # H2 Database set
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB (In-Memory Mode)
    #url: 'jdbc:h2:~/test'    # H2 DB (Embedded Mode)
    username: root        # H2 DB ID
    password: root        # H2 DB PW

  # H2 Console set
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA set
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # DB (none, create, create-drop, update, validate)
      ddl-auto: create
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
jwt:
  header: Authorization
  prefix: Bearer
  access-exp-time: 3600000
  refresh-exp-time: 864000000
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ

# swagger
springdoc:
  show-login-endpoint: true
  #api-docs:
    #path: /api-docs
